# Generated by Django 5.2.14 on 2026-05-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=180)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='grants.grant')),
            ],
            options={
                'ordering': ['line_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='grants.grant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
