# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budgetline',
            table='budget_lines',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='project_members',
        ),
        migrations.AlterModelTable(
            name='reallocationrequest',
            table='reallocation_requests',
        ),
    ]
