# Generated by Django 5.2.14 on 2026-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_created_by_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived_from_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
