# Generated by Django 5.2.14 on 2026-06-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=80, unique=True)),
                ('permission_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['permission_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_roles(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_role_permissions(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _seed_roles(apps):
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("accounts", "Permission")

    default_roles = [
        ("SUPER_ADMIN", "Super Administrator"),
        ("FINANCE_OFFICER", "Finance Officer"),
        ("PROJECT_MANAGER", "Project Manager"),
        ("EXECUTIVE_DIRECTOR", "Executive Director"),
        ("FIELD_STAFF", "Field Staff"),
        ("EXTERNAL_AUDITOR", "External Auditor"),
        ("DONOR_USER", "Donor User"),
    ]
    for role_key, role_name in default_roles:
        Role.objects.get_or_create(role_key=role_key, defaults={"role_name": role_name})

    default_permissions = [
        ("manage_users", "Manage Users"),
        ("manage_finance", "Manage Finance"),
        ("manage_projects", "Manage Projects"),
        ("view_audit_logs", "View Audit Logs"),
    ]
    for permission_key, permission_name in default_permissions:
        Permission.objects.get_or_create(
            permission_key=permission_key,
            defaults={"permission_name": permission_name},
        )


def _seed_role_permissions(apps):
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("accounts", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    super_admin = Role.objects.get(role_key="SUPER_ADMIN")
    for permission in Permission.objects.all():
        RolePermission.objects.get_or_create(role=super_admin, permission=permission)
