# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permission_role_alter_user_role_rolepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='passwordresetrequest',
            table='password_reset_requests',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permissions',
        ),
        migrations.AlterModelTable(
            name='systemsetting',
            table='system_settings',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
