# Generated by Django 5.2.14 on 2026-06-03

from django.db import migrations


def seed_permission_matrix(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("accounts", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    permissions = [
        ("manage_users", "Manage Users"),
        ("manage_roles", "Manage Roles"),
        ("manage_permissions", "Manage Permissions"),
        ("manage_settings", "Manage Settings"),
        ("manage_donors", "Manage Donors"),
        ("manage_projects", "Manage Projects"),
        ("manage_finance", "Manage Finance"),
        ("manage_reports", "Manage Reports"),
        ("manage_operations", "Manage Operations"),
        ("manage_testing", "Manage Testing"),
        ("manage_compliance", "Manage Compliance"),
        ("view_audit_logs", "View Audit Logs"),
    ]
    for permission_key, permission_name in permissions:
        Permission.objects.get_or_create(
            permission_key=permission_key,
            defaults={"permission_name": permission_name},
        )

    role_permissions = {
        "SUPER_ADMIN": [permission_key for permission_key, _ in permissions],
        "FINANCE_OFFICER": [
            "manage_donors",
            "manage_projects",
            "manage_finance",
            "manage_reports",
            "view_audit_logs",
        ],
        "PROJECT_MANAGER": [
            "manage_donors",
            "manage_projects",
            "manage_operations",
            "manage_testing",
        ],
        "EXECUTIVE_DIRECTOR": [
            "manage_donors",
            "manage_projects",
            "manage_finance",
            "manage_reports",
            "manage_settings",
            "manage_operations",
            "manage_testing",
            "manage_compliance",
            "view_audit_logs",
        ],
        "FIELD_STAFF": [
            "manage_donors",
            "manage_projects",
            "manage_operations",
            "manage_testing",
        ],
        "EXTERNAL_AUDITOR": [
            "manage_reports",
            "manage_compliance",
            "view_audit_logs",
        ],
        "DONOR_USER": [
            "manage_donors",
            "manage_projects",
            "manage_reports",
        ],
    }

    for role_key, permission_keys in role_permissions.items():
        role = Role.objects.get(role_key=role_key)
        for permission_key in permission_keys:
            permission = Permission.objects.get(permission_key=permission_key)
            RolePermission.objects.get_or_create(role=role, permission=permission)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_alter_notification_table_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_permission_matrix, migrations.RunPython.noop),
    ]
