# Generated by Django 5.2.14 on 2026-06-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_table_alter_donorcommunication_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcommunication',
            name='communication_type',
            field=models.CharField(choices=[('general', 'General'), ('acknowledgment', 'Acknowledgment'), ('update', 'Update'), ('newsletter', 'Newsletter')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='donorcommunication',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorcommunication',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorcommunication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_communications', to=settings.AUTH_USER_MODEL),
        ),
    ]
