# Generated by Django 5.2.14 on 2026-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donorcommunication_communication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcommunication',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
