# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankaccount_transaction_bank_account_bankstatement_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_accounts',
        ),
        migrations.AlterModelTable(
            name='bankstatement',
            table='bank_statements',
        ),
        migrations.AlterModelTable(
            name='bankstatementline',
            table='bank_statement_lines',
        ),
        migrations.AlterModelTable(
            name='expenseapproval',
            table='expense_approvals',
        ),
        migrations.AlterModelTable(
            name='reconciliation',
            table='reconciliations',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
