# Generated by Django 5.2.14 on 2026-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_bankaccount_table_alter_bankstatement_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'effective_date'), name='unique_currency_rate_per_date')],
            },
        ),
    ]
