# Generated by Django 5.2.14 on 2026-06-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_base_amount_transaction_currency_and_more'),
    ]

    operations = [
    ]
