# Generated by Django 5.2.14 on 2026-06-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_make_requisition_nullable'),
        ('requisitions', '0003_alter_requisition_table_alter_requisitionitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='requisitions.requisition'),
        ),
    ]
