# Generated by Django 5.2.14 on 2026-07-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donorcommunication_is_read'),
        ('finance', '0009_spendingalert_paymentbatch_periodclose_scheduledpayment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='donors.donor'),
        ),
    ]
