# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complianceitem',
            table='compliance_items',
        ),
    ]
