# Generated by Django 5.2.14 on 2026-06-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0003_donorcommunication_communication_type_and_more'),
        ('finance', '0005_transaction_base_amount_transaction_currency_and_more'),
        ('projects', '0004_alter_budgetline_table_alter_project_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('donation_type', models.CharField(default='one-time', max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='donors.donor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction')),
            ],
            options={
                'db_table': 'stripe_checkout_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(max_length=20)),
                ('status', models.CharField(default='active', max_length=50)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='donors.donor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'db_table': 'stripe_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
