# Generated by Django 5.2.14 on 2026-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='todo', max_length=30),
        ),
        migrations.AlterField(
            model_name='uatfeedback',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
