# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_validation', '0003_bugreport_releasenote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bugreport',
            table='bug_reports',
        ),
        migrations.AlterModelTable(
            name='releasenote',
            table='release_notes',
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_cases',
        ),
        migrations.AlterModelTable(
            name='uatfeedback',
            table='uat_feedback',
        ),
    ]
