# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_processdocument'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processdocument',
            table='process_documents',
        ),
        migrations.AlterModelTable(
            name='staffrequirement',
            table='staff_requirements',
        ),
    ]
