# Generated by Django 5.2.14 on 2026-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_processdocument_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdocument',
            name='flowchart',
            field=models.TextField(blank=True, help_text='Mermaid.js flowchart definition'),
        ),
    ]
