# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportdelivery_reportschedule'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
        migrations.AlterModelTable(
            name='reportdelivery',
            table='report_deliveries',
        ),
        migrations.AlterModelTable(
            name='reportschedule',
            table='report_schedules',
        ),
    ]
