# Generated by Django 5.2.14 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_requisitionitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisition',
            table='requisitions',
        ),
        migrations.AlterModelTable(
            name='requisitionitem',
            table='requisition_items',
        ),
    ]
